name: tests

on:
  push:
    branches:
      - work
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATA_BASE_DIR: ${{ runner.temp }}/data
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          pip install -e ".[dev]"
      - name: Prepare writable data dirs
        run: |
          mkdir -p "$DATA_BASE_DIR/pamphlets" "$DATA_BASE_DIR/system"
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q
