name: Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATA_BASE_DIR: ${{ runner.temp }}/data
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Prepare writable data dirs
        run: |
          mkdir -p "$DATA_BASE_DIR/pamphlets" "$DATA_BASE_DIR/system"
      - name: Run tests
        run: |
          pytest -q
